### ISSUE TITLE
One-To-Many

### ISSUE THREAD

**Issue by tommykennedy** [appscot/sails-orientdb#106]
I have a one-to-many relationship and I have represented the relationship below. I would expect to see it represented by a linkedlist in the parent model. However I do not see the profile_picture property being created of type linkedlist with ProfilePicture class type. Is there anyway to accomplish this on Sails-Orientdb or what is the intended behaviour of waterline orm?

User Model

    module.exports = {
    tableName: 'User',
    schema: true,

    attributes: {
        id: {
            type: 'string',
            primaryKey: true,
            columnName: '@rid'
        },
        username: {
            type: 'string',
            unique: true
        },
        email: {
            type: 'email',
            unique: true
        },
        profile_picture: {
            collection: 'ProfilePicture',
            via: 'user'
        }
    }
    };

and the ProfilePicture model

    module.exports = {
    tableName: 'ProfilePicture',
    attributes: {
        id: {
            type: 'string',
            primaryKey: true,
            columnName: '@rid'
        },
        user: {
            model: "User",
            required: true
        },
        filename: {
            type: 'string'
        },
        active: {
            type: "boolean"
        }
    }
    };

**Comment by dmarcelino** [comment]
Hi @tommykennedy, 

Sails-orientdb follows, what I believe, is the common way of representing a 1-to-many relationship in SQL which is by placing the FKey in the child record, [example from OrientDB manual](http://orientdb.com/docs/last/Tutorial-Relationships.html#1-to-many-relationship):
[![1-to-many-relationship](http://www.orientdb.org/images/rdbms-1toN.jpg)]

> Is there anyway to accomplish this on Sails-Orientdb or what is the intended behaviour of waterline orm?

I'm afraid not, not in any simple way. If you store your associations as you suggest you won't be able to make use of waterline associations, `.populate()` and nested creates/updates won't work.

**Comment by tommykennedy** [comment]
Thanks Mario,

Thats a pity. The linkedlist would of worked nice for my use case where I want to retrieve the last entry in profile_picture as the active Profile Picture. This would of been very fast.

I will have to create an unnecessary index on user in the ProfilePicture model and use an active flag. 

I might have to work outside waterline for this one.

**Comment by dmarcelino** [comment]
It's not easy to support all possible use cases for all DBs in a multi-adapter ORM...

> I might have to work outside waterline for this one.

That's definitely a valid option and `.getDB()` will give you all the power of Oriento! :wink:
