### ISSUE TITLE
cant run sails with orientdb

### ISSUE THREAD

**Issue by stuk88** [appscot/sails-orientdb#112]
here is the connections.js code added:
```
  localOrientServer: {
    adapter:'sails-orientdb',
    port: 2424,
    host: 'localhost',
    user: 'root',
    password: 'somepass',
    database: 'myApp'
  },
```

and i get this error:
```error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (e:\Projects\142-server\node_modules\sails\lib\app\private\loadHooks.js:92:21)
    at Timer.listOnTimeout (timers.js:110:15)```

**Comment by stuk88** [comment]
eventually i've set the _hookTimeout to 60000 and it went ok

**Comment by dmarcelino** [comment]
@stuk88, is this still an issue?

**Comment by stuk88** [comment]
yea... im still using hookTimeout so the orm will not crash.

**Comment by dmarcelino** [comment]
How many collections and how many records do you have? Also, are you running the DB in a different machine?

`migrate: 'alter'` reads all records into memory, destroys the schema, re-creates the schema and saves all records. So, depending on the number of records and collections this may take some time. `migrate: 'alter'` is performed by waterline core and it's not very efficient (balderdashy/waterline#635) so we can only recommend that you indeed increase the hookTimeout or use another strategy such as `'create'`.

**Comment by stuk88** [comment]
Thank you for the info :)
So I think you really should add that instruction to the install procedure... it took me time to resolve this issue.

**Comment by dmarcelino** [comment]
Which instruction? :)

The recomendation to use `migrate: 'create'` is on the README of sails-orientb.

The different `migrate` settings are a waterline feature (not an adapter feature). They are documented in the sails docs and should be documented on the waterline-docs.

**Comment by dmarcelino** [comment]
Closing this as inactive, please reopen if you feel this hasn't been fully answered.
