### ISSUE TITLE
On migrate: alter and drop, cant drop class

### ISSUE THREAD

**Issue by stuk88** [appscot/sails-orientdb#113]
This is the message I get:
```
com.orientechnologies.orient.core.exception.OCommandExecutionException: 
'DROP CLASS' command cannot drop class 'locations' because contains Vertices. 
Use 'DELETE VERTEX' command first to avoid broken edges in database, 
or apply the 'UNSAFE' keyword to force it [ONetworkProtocolHttpDb]
```

**Comment by dmarcelino** [comment]
Hi @stuk88, 

Which versions of OrientDB and sails-orientDB are you using?

Also which options are you using, namely `unsafeDrop`?

**Comment by stuk88** [comment]
orientdb-community-2.0.6
sails-orientdb 0.10.55

**Comment by stuk88** [comment]
after adding unsafeDrop it seems, alter is working now.

**Comment by dmarcelino** [comment]
`'alter'` is not [really supported](https://github.com/appscot/sails-orientdb#sails-orientdb):

> We don't recommend using `migrate: 'alter'` as it has the nasty effect of deleting the data of all edges on a graphDB, leaving only data on the vertexes.

But `'drop'` should work. Let me know if the issues persist.

**Comment by dmarcelino** [comment]
Closing this as inactive, please reopen if you feel this hasn't been fully answered.
