### ISSUE TITLE
Production / Development connections handling

### ISSUE THREAD

**Issue by stuk88** [appscot/sails-orientdb#114]
I have tried to add two connections to the main connections.js file, both for sails-orientdb,
one for local, and other for remote.
pulled my hairs for a long time figuring out why the connection is refused, 
eventually after getting the logs working (they should be working by default in sails verbose state)
I found out that sails-orientdb is trying to connect to both local and remote connections at the same time.

I had to separate both connection to their env file accordingly. 
development.js
production.js

Is that a bug of sails-orientdb?

**Comment by dmarcelino** [comment]
> eventually after getting the logs working (they should be working by default in sails verbose state)

@stuk88, I believe you're mistaken here. `sails-orientdb` and `waterline` are independent of sails. As far as i know there is no (public) API in waterline to enable logging in the adapters.

The waterline docs are not very explicit about this in the docs but Waterline is able to connect to several different datastores simultaneously. If you define multiple connections the assumption is that you are accessing multiple datastores, hence the error that you've experienced.

BTW, at the model level you can define to which connection the model belongs to by setting `connection`:
https://github.com/balderdashy/waterline-docs/blob/master/models/models.md#model-property-summary

> Is that a bug of sails-orientdb?

No, doesn't look like it.

**Comment by stuk88** [comment]
Even though the connection is failing even if there is one connection that is wrong all the connections are failing.
Its a oriento architecture that causes that behaviour:

file: oriento/lib/transport/binary/connection.js
line: 164
```
 this.socket.once('error', function (err) {
      this.logger.debug('connection error during negotiation: ' + err);
--->this.socket.removeAllListeners();
      this.connecting = false;
      reject(new errors.Connection(err.code, err.message));
    }.bind(this));
```

**Comment by dmarcelino** [comment]
So... this is not a sails-orientdb issue, right?

**Comment by dmarcelino** [comment]
Closing this as inactive, please reopen if you feel this hasn't been fully answered.
