### ISSUE TITLE
How can I make transactions with sails-orientdb.

### ISSUE THREAD

**Issue by tampham47** [appscot/sails-orientdb#121]

**Comment by dmarcelino** [comment]
Hi @tampham47, 

Waterline, and consequently, sails-orientdb do not support transactions. However, Oriento supports them and sails-orientdb exposes Oriento, so you can do something like:

```js
var db = itemsModel.getDB();

// using oriento syntax, you can do something like
var tx = db.begin();
tx.create({
  '@class': 'TestClass',
  name: 'item3'
});
return tx.commit()
.then(function (results) {
  console.log(results.created.length);  // should be 1
});
```

You can find more details in http://stackoverflow.com/a/29238714/4249576.

**Comment by dmarcelino** [comment]
Feel free to re-open if this doesn't fully answer your question.

**Comment by tampham47** [comment]
Thanks for your answer, 
How can I rollback when I got something wrong, I have tried to call .rollback() function, but it's not define.
