### ISSUE TITLE
How can I rollback with sails-orientdb?

### ISSUE THREAD

**Issue by tampham47** [appscot/sails-orientdb#123]
Hi,

I wanna to rollback incase my query got errors, something like this (http://stackoverflow.com/questions/29586175/waterline-transaction-through-sails-orientdb), but rollback function at sails-orientdb is not defiend.

```javascript
var db = itemsModel.getDB();
var trans = db.begin();
trans.update('items')
     .set({status:UNAVAILABLE})
     .where({id:items_ids_list,status:AVAILABLE}).exec()
     .then(function(items){ 
         if (items.length != items_ids_list.length) {
             trans.rollback(); /* send error here*/
         } else trans.commit();
     });
```

So how can I do that?

Thanks,

**Comment by dmarcelino** [comment]
Hi @tampham47, once you do `var db = itemsModel.getDB();` you are using an [Oriento](https://github.com/codemix/oriento) database object and as such you need to use Oriento syntax. Waterline does not support transactions and neither does sails-orientdb.

**Comment by tampham47** [comment]
Hi @dmarcelino, Have you had a plan to support transactions for sails-orientdb?

**Comment by dmarcelino** [comment]
Not until waterline supports them: balderdashy/waterline#755.

**Comment by tampham47** [comment]
@dmarcelino thanks, I am looking forward to seeing it :smile:
