### ISSUE TITLE
Any plans on updating for the new OrientJS?

### ISSUE THREAD

**Issue by vinerz** [appscot/sails-orientdb#124]
Now that Oriento is deprecated, giving place to OrientJS maintained by OrientDB team, are there any plans to update this layer to the new library?

Thank you all for the wonderful work.

**Comment by nafetswirth** [comment]
+1

**Comment by tommykennedy** [comment]
+1

**Comment by dmarcelino** [comment]
Eventually. Current npm version of OrientJS is https://github.com/orientechnologies/orientjs/commit/e7cf8c2ab0673233ef27ea738eaa4e4cfabeda18 (it's hard to say because it's not tagged) doesn't include PR codemix/oriento#330, so it has no benefits over Oriento. After OrientJS releases a newer version with added features/fixed issues we'll update to OrientJS.

**Comment by nidaca** [comment]
+1

**Comment by AndreaPravato** [comment]
+1

**Comment by lvca** [comment]
Hey guys, I merged it in OrientJS

**Comment by baltag** [comment]
Thanks @lvca. Now @dmarcelino may start to integrate it into sails-orientdb.

**Comment by nidaca** [comment]
:+1: ... means this that we must prepare also for the 2.1 OrientDB snapshot in the same time with an update of the driver, or (for the start) it will work with the current 2.0 ?

**Comment by dmarcelino** [comment]
That's cool @lvca but those changes haven't reached [npm](http://www.avsforum.com/forum/145-htpc-gaming/1326722-pc-connected-hdtv-via-hdmi-very-dark-picture-saturated-colour.html#post20422181):

<img width="1073" alt="screen shot 2015-09-25 at 09 57 44" src="https://cloud.githubusercontent.com/assets/1280446/10096749/00f5227c-636c-11e5-887e-3d109628e8b3.png">

**Comment by lvca** [comment]
Hey @dmarcelino you're right. Sorry, but I'm not still very good at this Node.js stuff ;-) Done, right now.

**Comment by baltag** [comment]
Great, thanks

**Comment by vinerz** [comment]
Awesome! Thank you guys :)
