### ISSUE TITLE
LinkedList Type

### ISSUE THREAD

**Issue by tommykennedy** [appscot/sails-orientdb#125]
Hi Dario,

How do I use LinkedList instead of EmbeddedList when defining a type as array

        experience: {
            type: 'array'
        }

Tom

**Comment by dmarcelino** [comment]
Hi @tommykennedy, currently that's not possible and building a workaround would probably be a pain... Supporting that scenario will become easier once balderdashy/waterline#981 goes in. Having said that, if you can think of an elegant solution feel free to PR.

**Comment by tommykennedy** [comment]
I will prob have to work outside the ORM for this 

Thanks for the guidance and hopefully 981 gets implemented soon
