### ISSUE TITLE
How do I "CREATE CLASS Cat EXTENDS Pet ABSTRACT;" in sails-orientDB using waterline?

### ISSUE THREAD

**Issue by ipalfy** [appscot/sails-orientdb#127]

**Comment by dmarcelino** [comment]
Hi @ipalfy, Waterline does not support the concept of abstract classes so you have to either use [.query()](https://github.com/appscot/sails-orientdb#query-query--options-cb) to run any SQL query or use [.getDB()](https://github.com/appscot/sails-orientdb#getdb-) to get a node.js driver DB object which uses the Oriento/OrientJS syntax.
