### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by nomi-ramzan** [appscot/sails-orientdb#132]
Hi
Why we need internet connection to connect with orientDB ( running local ) ?
If u put offline your computer then you can not connect to orientdb even if it is running on same machine.

**Comment by dmarcelino** [comment]
Hi @nomi-ramzan, I've just tried running an application that connects to orientdb on my machine, offline, and everything worked. Can you share your logs?

**Comment by nomi-ramzan** [comment]
Here is log. if system is connected with wifi/lan then its working fine. otherwise i am getting this error on win 8 OS.

``` Unhandled rejection OrientDB.ConnectionError [ENOENT]: getaddrinfo ENOENT
    at Connection.<anonymous> (D:\WorkingDIR\modules\combine_app\node_modules\sa
ils-orientdb\node_modules\oriento\lib\transport\binary\connection.js:166:14)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)  ```

**Comment by dmarcelino** [comment]
Can you share your configuration?

**Comment by nomi-ramzan** [comment]
Here are configurations which I am using

``` var orientAdapter = require('sails-orientdb');
var config = {adapters: {'default': orientAdapter,orient: orientAdapter,},connections: {myLocalOrient: {adapter: 'orient',host: 'localhost',port:2424,user: 'root',password: 'root',database: 'db_final'}},defaults: {migrate: 'safe'}}; ```Here are configurations which I am using

``` var orientAdapter = require('sails-orientdb');
var config = {adapters: {'default': orientAdapter,orient: orientAdapter,},connections: {myLocalOrient: {adapter: 'orient',host: 'localhost',port:2424,user: 'root',password: 'root',database: 'db_final'}},defaults: {migrate: 'safe'}}; ```

**Comment by dmarcelino** [comment]
I can't think of a reason why you are experiencing that issue but I don't think it's being caused by `sails-orientdb`. It's probably worth asking the `OrientDB` folks about it.

**Comment by nomi-ramzan** [comment]
I also have the same ide. this problem is maybe due to oriento. can you please tell me your oriento version.

**Comment by dmarcelino** [comment]
1.2.0

**Comment by nomi-ramzan** [comment]
I am using 1.1.3. If I will update just oriento only. Is there any problem with sails-orientdb package ?

**Comment by dmarcelino** [comment]
No.

**Comment by nomi-ramzan** [comment]
Thank you

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open if you feel otherwise

**Comment by joovin** [comment]
I got same problem

**Comment by joovin** [comment]
Previously I had Ubuntu 15.10 there is no problem I can run sails with Internet and without also
But when I shift to Windows 7 there is a problem
Connection error in sails orientdb

**Comment by dmarcelino** [comment]
Hi @joovin, I don't have a windows PC to test this. Have you tried connecting to OrientDB using only Oriento/OrientJS to see if the problem lies there? Which version of OrientDB are you using?
