### ISSUE TITLE
it still uses oriento instead of orientjs

### ISSUE THREAD

**Issue by webmasterslava** [appscot/sails-orientdb#144]
```
npm cache clean
npm install sails-orientdb
```

/node_modules/sails-orientdb/package.json

```
"version": "0.10.55",
"dependencies": {
  "oriento": "~1.1.0",
}
```

looks like this repo is not synced with npm registry, because this command
`npm install git://github.com/appscot/sails-orientdb.git`
installs the module with orientjs dependency.

**Comment by kalenchikov** [comment]
+1

**Comment by andreipop-reea** [comment]
+1

**Comment by dmarcelino** [comment]
Hi @webmasterslava, v0.10.60 has been released. Thanks
