### ISSUE TITLE
populate in and out values of edge

### ISSUE THREAD

**Issue by nomi-ramzan** [appscot/sails-orientdb#72]
Hi !
How can I populate in and out values( links ) in waterline-sails or waterline-orientdb ?
Like
SELECT *, in.*, out.* FROM sellings
in waterline
sellingsModel.find({id:'12:0'}).populate('in').populate('out')

**Comment by dmarcelino** [comment]
Hi @nomi-ramzan, depends on your model definitions, the only way I can think of is by using [many-to-many *through* associations](https://github.com/appscot/sails-orientdb#examples) but given that those are [not yet officially supported by waterline](balderdashy/waterline#705) you would be venturing into new territory. Apart from that you can use `model.query()` with a fetch plan SQL query such as the one I've mention in [stackoverflow](http://stackoverflow.com/a/29286260/4249576).

**Comment by dmarcelino** [comment]
Closing this for now, please reopen if have any other queries pertaining this topic.
