### ISSUE TITLE
.query promises

### ISSUE THREAD

**Issue by tommykennedy** [appscot/sails-orientdb#73]
Hi Dario,

I am looking to use promises with the .query method but I get back.

TypeError: Cannot call method 'then' of undefined

Does this not work with Promises?

        User.query("select @rid from User where username='" + req.param("userid") + "'").then(function(userData){
            console.log(userData);
            return res.json({status:"success"});
        }).fail(function (err) {
            console.log("Handled");
            return res.json({status:"failed"});
        });

**Comment by dmarcelino** [comment]
Hi @tommykennedy, `.query()` does not support promises, it uses callbacks. Example in:
https://github.com/appscot/sails-orientdb#query-query--options-cb

If you really need promises, you can promisify it using [bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function):
```javascript
var readFile = Promise.promisify(require("fs").readFile);
```
