### ISSUE TITLE
COUNT and SUM in same query

### ISSUE THREAD

**Issue by nomi-ramzan** [appscot/sails-orientdb#75]
Hi !
How can I COUNT and SUM items like 
select SUM(price) AS total, COUNT(id) AS total_items from items in waterline / sails-oreintdb
Here is my code
itemModel.find( { where: { price: { '<=' : 5000 } }, sum: [ 'price' ], count: true })
and result is just sum ( "price": 4297 ).

Thanks

**Comment by dmarcelino** [comment]
Hi @nomi-ramzan,

Please note that sails-orientdb is an [adapter](http://en.wikipedia.org/wiki/Adapter_pattern) for waterline and as such it uses the same syntax as described in the [Waterline Project](https://github.com/balderdashy/waterline) / [Waterline Documentation](https://github.com/balderdashy/waterline-docs). The only exception to this are a few custom methods to help with specific OrientDB operations which are described in [sails-orientdb main page](https://github.com/appscot/sails-orientdb#methods). You will receive better replies to this question if you ask this on the [Waterline Project](https://github.com/balderdashy/waterline), [StackOverflow tag: waterline](http://stackoverflow.com/questions/tagged/waterline) or [Sails gitter channel](https://gitter.im/balderdashy/sails).

You should be able to do this by:

* using 2 operations:
   + `.find( { where: { price: { '<=' : 5000 } }, sum: [ 'price' ])`;
   + `.count(/*criteria*/)`.
* or using `.query(/*SQL query*/)`
