### ISSUE TITLE
Allow specification of index engine type

### ISSUE THREAD

**Issue by nkibler7** [appscot/sails-orientdb#77]
I don't see this anywhere in the README, but it would be nice to be able to specify the index engine type for an attribute. OrientDB supports the use of these indexes (http://orientdb.com/docs/last/Indexes.html) and has several different types to specify. The default is to use an SB-Tree with a NOTUNIQUE type, but if I don't need to do range predicates, a Hash index would be much faster and more lightweight.

**UPDATE:** I took a look through the source code and it looks like it is supported. Just specify the name of the index type you want to use as a string for the "index" key in the attribute. Here is a list of supported index types:
* unique
* notunique
* fulltext
* dictionary
* unique_hash_index
* notunique_hash_index
* fulltext_hash_index
* dictionary_hash_index

Can this be added to the README?

**Comment by dmarcelino** [comment]
Hi @nkibler7, thanks for the suggestion, a PR would be welcomed! Usage - models section looks like a good place: https://github.com/appscot/sails-orientdb/blob/master/README.md#models-1

**Comment by dmarcelino** [comment]
Fixed via PR #83.
