### ISSUE TITLE
Edge count

### ISSUE THREAD

**Issue by zeeshanalisyed** [appscot/sails-orientdb#78]
I was trying to execute edgeModel.count({userid: req.params.id}).exec(function(err,success){}); but this function is not working for edges.

**Comment by dmarcelino** [comment]
Hi @zeeshanalisyed,

Can you please answer/provide:
* is `edgeModel` a join table of a [through association](https://github.com/appscot/sails-orientdb#many-to-many-through-associations)?
* your model definitions;
* the result of `console.log(req.params.id);` before running count?
* edgeModel.find({userid: req.params.id}).exec(function(err, edges){ console.log(edges); });

**Comment by zeeshanalisyed** [comment]
yes, it is a join table through association
Model definitions: 
edgeModel  = {
     identity:'sellings',
      connection: 'myLocalOrient',
      attributes:{
      	price:{type:'float', columnName:'price'},
      	currency:{type:'string', columnName:'currency' },
      	condition:{type:'integer', columnName:'condition'},
      	product:{
                  columnName: 'in',
                  type: 'string',
                  foreignKey: true,
                  references: 'products',
                  on: 'id',
                  onKey: 'id',
                  via: 'seller'
            },
      	seller:{
                  columnName: 'out',
                  type: 'string',
                  foreignKey: true,
                  references: 'users',
                  on: 'id',
                  onKey: 'id',
                  via: 'product'
            }
      }
    
};

Now when ever I execute following query 
edgeModel.count({seller: '#'+req.params.id}).exec(function(err,counts){ console.log(counts) });
I don't get any result in the count.

console.log(req.params.id); ===> result: 29:26 

result of edgeModel.find({seller: '#'+req.params.id}).exec(function(err, edges){ console.log(edges); });
is "undefined"

**Comment by dmarcelino** [comment]
@zeeshanalisyed, that's not supported (yet). `seller` is not a field but a representation of an association and currently Waterline doesn't provide an API to do that. To make things worse through associations are also not officially supported (balderdashy/waterline#705).

Your best option for now is to use [`.query()`](https://github.com/appscot/sails-orientdb#query-query--options-cb).

**Comment by zeeshanalisyed** [comment]
Ok and there is no performance isssue while using query function?

**Comment by dmarcelino** [comment]
`.query()` calls Oriento's (official OrientDB driver) own `.query()` function so there won't be any performance issues.

**Comment by zeeshanalisyed** [comment]
Ok, thank you that was really helpful.
