### ISSUE TITLE
alter command removes all the edges

### ISSUE THREAD

**Issue by zeeshanalisyed** [appscot/sails-orientdb#79]
whenever I configure sails-orientdb adapter with migrate 'alter' command it removes all the edges which are existing inside my database and somehow if I am not wrong why it changes rids of the existing vertices?

**Comment by dmarcelino** [comment]
Hi @zeeshanalisyed, this is known behaviour and is documented on the top of the README:

> Migrations
>
> We don't recommend using migrate: 'alter' as it has the nasty effect of deleting the data of all edges on a graphDB, leaving only data on the vertexes. Either use 'safe' and migrate manually or use 'drop' to completely reset the data and collections. In production always use 'safe'. We are currently pushing for a new kind of migration strategy named 'create', check waterline issue #846.

'alter' is an experimental migration and is handled by waterline core, there is nothing we can do from the sails-orientdb side.

**Comment by zeeshanalisyed** [comment]
ok thank you  @dmarcelino
