### ISSUE TITLE
Association mapping problem

### ISSUE THREAD

**Issue by zeeshanalisyed** [appscot/sails-orientdb#80]
I tried to map one-many relationship but for example I have a pet class and a user class user has many pets so schema field will contain on the side of user                                                                           pets:{ 
collection:'pet',
 via: 'owner'
}
and pet will contain 
owner :{ model:'user' } 
but whenever i try to map this assocation through sails-orientdb it down not show create any field with type linkset and linked_class : pet.

**Comment by dmarcelino** [comment]
Hi @zeeshanalisyed,

As per the sails-orientdb [README](https://github.com/appscot/sails-orientdb#one-to-many-associations):
> One-to-Many Associations are also represented by LINKs in OrientDB.

In other words, no `linkset` is created as that would be redundant. If you take a look at [OrientDB relationships docs](http://orientdb.com/docs/last/orientdb.wiki/Tutorial-Relationships.html#1-to-many-relationship) you can see that there is only a single reference from one record to another and no need to create a structure similar to a `linkset`.

Please reopen if the answer doesn't fully answer your question.

**Comment by nidaca** [comment]
I have one question on this problem. If you perform a populate on the 'user' side (the collection side) on 'pets' association, if you don't have a linkset behind the scene, the database will do a search (indexed or not) on the pets cluster to match the user's id with the 'owner' link property (like an old fashion join). Is that correct ... and, if it is, this will not have an impact to the performance on the "big data" world ? It would be nice to populate this association with zero performance impact, directly through linksets. Is this possible ?

**Comment by nidaca** [comment]
... at least it could be possible to use a linkset only for 'collection' associations without a 'via' redirection (only one side association).

**Comment by dmarcelino** [comment]
Hi @nidaca 

> If you perform a populate on the 'user' side (the collection side) on 'pets' association, if you don't have a linkset behind the scene, the database will do a search (indexed or not) on the pets cluster to match the user's id with the 'owner' link property (like an old fashion join). Is that correct ..

Currently it would behave similarly to a SQL `JOIN`, yes. In other words it's a [many-to-one association](http://orientdb.com/docs/last/orientdb.wiki/Concepts.html#1-1-and-n-1-referenced-relationships).

> this will not have an impact to the performance on the "big data" world ? 

If performance is important then it's probably best to use a many-to-many association for now as that will use fetch plans during retrieval without a lookup.

> It would be nice to populate this association with zero performance impact, directly through linksets. Is this possible ?
> ... at least it could be possible to use a linkset only for 'collection' associations without a 'via' redirection (only one side association).

Not currently. Waterline itself (sails-orientdb is just an adapter) doesn't support the concept of one-way-many association: http://stackoverflow.com/questions/30198701/sails-js-is-there-intended-support-for-a-one-way-many-association

Unless you are comfortable using [native queries](https://github.com/appscot/sails-orientdb#query-query--options-cb) or [Oriento directly](https://github.com/appscot/sails-orientdb#getdb-) but these options won't return waterline models.

**Comment by nidaca** [comment]
Ok, I understand. Thank you for the response.
Related to the link you gave me, I have a simple example:

// Color.js
module.exports = {
	......
	joinTableNames : {
		labels : 'labeled'
	},
	attributes : {
		labels : {
			collection : 'label',
			via : 'colors',            // 1 - can this property be commented ?
			dominant : true
		}
	}
};

// Label.js
module.exports = {
        ........
	attributes : {
		colors : {                         // 2 - can this attribute be commented ?
			collection : 'color',
			via : 'labels'
		}
	}
};

1 - This will work, but if I comment the 'via' property from the color model it doesn't work anymore. It gives me an error on waterline loading:
'Trying to associate a collection attribute to a model that doesn't have a Foreign Key. label is trying to reference a foreign key in color'
Shouldn't this be an allowed change ?

2 - Shouldn't be an allowed change the commenting of the whole 'colors' attribute from the label model ? (as in the example from the stackoverflow link). Now it gives me an run time error:
'Cannot read property 'out' of null at C:\...\node_modules\sails-orientdb\lib\associations.js:86:17'

I am trying to make two models: Color and Somethingelse that links to the Label model through one to many relations / associations (I need only one way traversal), but the two ('labels') relations are mapped to the same 'labeled' OrientDB edge class. How can I do that ?

**Comment by nidaca** [comment]
I mean the general question here is how can I define a many (to one / many) association without referencing the peer association in the association's model or even not defining one. Thank you very much ...

**Comment by dmarcelino** [comment]
1. No that's not allowed because otherwise waterline does not know the other side of the association. Check [waterline many-to-many docs](https://github.com/balderdashy/waterline-docs/blob/master/models/associations/many-to-many.md)

2. No, waterline does not support one-way-many associations. Even if it works in a given adapter it's not generally supported.

> I am trying to make two models: Color and Somethingelse that links to the Label model through one to many relations / associations (I need only one way traversal), but the two ('labels') relations are mapped to the same 'labeled' OrientDB edge class. How can I do that ?

There's a lot of info there... 

> mapped to the same 'labeled' OrientDB edge class

By default waterline manages the junction tables (equivalent to edges) and controls both their name and schema. sails-orientdb allows to [override the junction table name](https://github.com/appscot/sails-orientdb#custom-edge-names-optional) but this will probably wouldn't be enough for you to run 2 different associations through it.

Another option would be [many-to-many trough association](https://github.com/balderdashy/waterline-docs/blob/master/models/associations/many-to-many-through.md) that allows you to the define the schema of the junction table but these are [not officially supported](https://github.com/balderdashy/waterline/issues/705#issuecomment-60945411) yet.

Also, if you want to use edges, you can't use a one-to-many association (those use a `LINK`) but you'll have to use many-to-many associations which uses edges.

One way to go about this is to forego the edge named 'labeled' for something like 'labeled_Color' and 'labeled_Somethingelse' then it's just a matter of defined 2 many-to-many associations similarly to what you've done in your example.

Part of the reason why it's so difficult to model your specific use case in waterline is because waterline does not support abstract models: balderdashy/waterline#581

**Comment by nidaca** [comment]
I managed to do something like this:

// Color.js
module.exports = {
    ......
    joinTableNames : {
        labels : 'labeled'
    },
    attributes : {
        labels : {
            collection : 'label',
            via : 'colors',
            dominant : true
        }
    }
};

// Material.js
module.exports = {
    ......
    joinTableNames : {
        labels : 'labeled'
    },
    attributes : {
        labels : {
            collection : 'label',
            via : 'materials',
            dominant : true
        }
    }
};

// Label.js
module.exports = {
    ........
    attributes : {
        colors : {
            collection : 'color',
            via : 'labels'
        },
        materials : {
            collection : 'material',
            via : 'labels'
        }
    }
};

So, I have two many to many associations that shares the same edge class / cluster 'labeled'.

**Comment by dmarcelino** [comment]
Good stuff, glad you managed to find a workaround! :grinning: 

Just bear in mind that is not a foreseen scenario and hence there are no guarantees it will keep working in future versions.
