### ISSUE TITLE
Save many to many relation (populated model) problem

### ISSUE THREAD

**Issue by anthonybriand** [appscot/sails-orientdb#89]
Hello,

There is a problem when I save a many-to-many relation populated model, the save callback will never be called and the record is updated continuously : 

There is an example to reproduce : 
```javascript
User.findOne(user.id).populate("roles").exec(function (err, user) {
    Role.findOne({name: "registered"}).exec(function (err, role) {
        user.roles.add(role.id); // Or user.roles.add(role);
        user.save(function (err, updatedUser) {
            // Will never be called and record is updated continuously
        });
    });
});
```

Sails version : 0.11
sails-orientdb : 0.10.50

**Comment by dmarcelino** [comment]
Hi @anthonybriand, I've created a test for this in [balderdashy/waterline-adapter-tests#61](https://github.com/balderdashy/waterline-adapter-tests/pull/61/files#diff-89dc069f201edf0d91744b9be62268a8R96):
``` javascript
      it('after populating parent should link a payment to a customer through a join table', function(done) {
        Associations.Driver.findOne(driverRecord.id)
        .populate('taxis')
        .exec(function(err, driver) {
          driver.taxis.add(taxiRecord2.id);
          driver.save(function(err) {
            assert(!err);
  
            // Look up the driver again to be sure the taxi was added
            Associations.Driver.findOne(driverRecord.id)
            .populate('taxis', { medallion: 30 })
            .exec(function(err, data) {
              assert(!err);
  
              assert(data.taxis.length === 1);
              assert(data.taxis[0].medallion === 30);
              done();
            });
          });
        });
      });
```

and sails-orientdb passes it. Did I miss something? Alternativey can you provide a failing test for this?

**Comment by dmarcelino** [comment]
A couple of questions:
* does your code works with other adapters?
* can you provide your model definitions?

**Comment by anthonybriand** [comment]
I am not familiar with unit testing, sorry.

It's working well with sails-disk and sails-mysql.

Sure : 
User.js
```javascript
attributes: {
    username: {
        type: 'string',
        required: true,
        alphanumericdashed: true
    },
    email: {
        type: 'email',
        required: true
    },
    roles: {
        collection: 'Role',
        via: 'users',
        dominant: true
    }
}
```

Role.js
```javascript
attributes: {
    name: {
        type: 'string',
        index: true,
        notNull: true,
        unique: true
    },
    users: {
        collection: 'User',
        via: 'roles'
    },
    active: {
        type: 'boolean',
        defaultsTo: true,
        index: true
    }
}
```

There is the full code I have used to produce this problem : 
```javascript
User.create({
        username: "aaa",
        email: "bbb@aaa.com",
        password: "zzzzzzzz"
}).exec(function (err, ouser) {
    if (err) {
        return res.negotiate(err);
    }
    User.findOne(user.id).populate("roles").exec(function (err, user) {
        if (err) {
            return res.negotiate(err);
        }

        Role.findOne({name: "registered"}).exec(function (err, role) {
            if (err) {
                return res.negotiate(err);
            }
            user.roles.add(role.id);

            user.save(function (err, updated) {
                if (err) {
                    return res.negotiate(err);
                }

                res.ok(updated);
            });
        });
    });
});
```

**Comment by dmarcelino** [comment]
Lets try to diagnose the issue in your machine then:

* At `User.findOne(user.id)`, `user` is not defined yet, shouldn't it be `ouser`?
* `user.save(function (err, updated) {`, the callback for `user.save()` only returns error, not the updated record so you should drop `updated` from there.
* can you try removing the `.populate("roles")` to see if it works? Just to understand if that has anything to do with the issue.
* before `user.roles.add(role.id);` please add `console.log('role:', role);` to see what is actually being added.

**Comment by anthonybriand** [comment]
* Yes of course it's a typing error, sorry
* Ok, it's an OrientDB limitation ? Because with sails-mysql it return the updated model
* If I remove the .populate the save works fine
* Below the log for role : 
```javascript
role: { name: 'registered',
  active: true,
  createdAt: Thu Apr 30 2015 16:01:10 GMT+0200 (CEST),
  updatedAt: Thu Apr 30 2015 16:01:10 GMT+0200 (CEST),
  id: '#15:1' }
```

**Comment by dmarcelino** [comment]
* It's not on the [docs](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#when-both-records-exist) nor on the [.add() tests](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/manyToMany/add.js). If sails-mysql (or even sails-orientdb) supports it it's not *official* nor guaranteed to always work. So I would say it's a case of "use it at your own risk" :smiley:
* not sure why `.populate()` causes this, in the balderdashy/waterline-adapter-tests#61 test it worked fine...
* all seems good there.

Can you [enable sails-orientdb logging](https://github.com/appscot/sails-orientdb/blob/master/CONTRIBUTING.md#try-the-latest-version-of-sails-orientdb) and check if any relevant output is thrown when `user.save()` is executed?

**Comment by anthonybriand** [comment]
```javascript
sails-orientdb:document:debug Update [user] with values: [object Object]
___Inspected object #1___
{ owner: { [String: '#17:1'] cluster: 17, position: 1 },
  username: 'aaa',
  email: 'bbb@aaa.com',
  createdAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  updatedAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  '@rid': undefined } +5ms
  sails-orientdb:document:debug Update where query:  @rid = :param0  +1ms
  sails-orientdb:document:debug Update params: [object Object]
___Inspected object #1___
{ param0: { [String: '#17:1'] cluster: 17, position: 1 } } +0ms
  sails-orientdb:document:debug Update results: 1 +2ms
  sails-orientdb:document:debug Find query: SELECT @rid, in AS role_users, out AS user_roles  FROM role_users__user_roles  WHERE out.toLowerCase() = :param0  +6ms
  sails-orientdb:document:debug Find params: { params: { param0: '#17:1' } } +1ms
  sails-orientdb:document:debug Find results: 0 +5ms
  sails-orientdb:document:debug Update [user] with values: [object Object]
___Inspected object #1___
{ username: 'aaa',
  email: 'bbb@aaa.com',
  createdAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  updatedAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  owner: { [String: '#17:1'] cluster: 17, position: 1 },
  '@rid': undefined } +7ms
  sails-orientdb:document:debug Update where query:  @rid = :param0  +1ms
  sails-orientdb:document:debug Update params: [object Object]
___Inspected object #1___
{ param0: { [String: '#17:1'] cluster: 17, position: 1 } } +0ms
  sails-orientdb:document:debug Update results: 1 +3ms
```
And it infinitely redo this part : 
```javascript
sails-orientdb:document:debug Update [user] with values: [object Object]
___Inspected object #1___
{ username: 'aaa',
  email: 'bbb@aaa.com',
  createdAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  updatedAt: Thu Apr 30 2015 16:15:06 GMT+0200 (CEST),
  owner: { [String: '#17:1'] cluster: 17, position: 1 },
  '@rid': undefined } +8ms
  sails-orientdb:document:debug Update where query:  @rid = :param0  +0ms
  sails-orientdb:document:debug Update params: [object Object]
___Inspected object #1___
{ param0: { [String: '#17:1'] cluster: 17, position: 1 } } +1ms
  sails-orientdb:document:debug Update results: 1 +2ms
```

**Comment by dmarcelino** [comment]
`{ owner: { [String: '#17:1'] cluster: 17, position: 1 },`, what is owner? Didn't see it on your model definitions...

What versions of waterline and OrientDB are you using?

**Comment by anthonybriand** [comment]
Waterline : 0.10.18, OrientDB : 2.0.6, Sails : 0.11, sails-orientdb : 0.10.50

Sorry :confounded:, it's an automatic field added by sails-permissions to set who is the owner of the record.

I am really sorry it's my fault, the owner field not have to be here, this generate a circular dependency to the user and cause the infinite loop on save.

All my apologies about this.

**Comment by dmarcelino** [comment]
Ah, interesting... No worries, nothing to apologise, we both learned something out of this!

**Comment by dmarcelino** [comment]
BTW @anthonybriand, there has been [lots of changes](https://github.com/balderdashy/waterline/compare/v0.10.18...master) in waterline since v0.10.18, you may want to update it.

**Comment by anthonybriand** [comment]
OK :smile: thank you for all
